notifications:
  recipients:
    - koji.shimada@enishi-tech.com
    - adzuki34@gmail.com
language: ruby
rvm:
  - 1.9.3
install:
  - curl https://raw.github.com/groonga/groonga/master/data/travis/setup.sh | sh
  - bundle install
