notifications:
  recipients:
    - koji.shimada@enishi-tech.com
    - adzuki34@gmail.com
language: ruby
rvm:
  - 1.9.3
before_install:
  - curl --silent --location https://github.com/groonga/groonga/raw/master/data/travis/setup.sh | sh
